# Generated by Django 5.0.2 on 2025-02-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_cryptocoins_contracts_contract_crypto_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='crypto_coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='Main.cryptocoins'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='market_price',
            field=models.FloatField(blank=True),
        ),
    ]
