# Generated by Django 5.0.2 on 2025-02-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_contract_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='market_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
