# Generated by Django 5.0.2 on 2025-02-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_contract_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='market_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
