# Generated by Django 5.0.2 on 2025-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_contract_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='market_price',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
