# Generated by Django 5.0.2 on 2025-02-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_contract_market_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_short',
            field=models.BooleanField(default=False),
        ),
    ]
